version: 2
updates:
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    # Workflow files stored in the default location of `.github/workflows`
    # You don't need to specify `/.github/workflows` for `directory`. You can use `directory: "/"`.
    directory: "/"
    target-branch: "OA-2581-Setup-dependabot-to-create-PRs-to-update-actions"
    # target-branch: "develop"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
      timezone: "Europe/Stockholm"

  # Enable version updates for Docker Actions
  - package-ecosystem: "docker"
    # Directory containing the Dockerfile to monitor for base image updates
    directory: "/docker"
    target-branch: "OA-2581-Setup-dependabot-to-create-PRs-to-update-actions"
    # target-branch: "develop"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:30"
      timezone: "Europe/Stockholm"
