#'Easy volcano plot with Olink theme
#'
#'Generates a volcano plot using the results of the olink_ttest function using ggplot and ggplot2::geom_point.
#'The estimated difference is plotted on the x-axis and the negative 10-log p-value on the y-axis.
#'The horizontal dotted line indicates p-value=0.05.
#'Dots are colored based on the Benjamini-Hochberg adjusted p-value cutoff 0.05 and can optionally be annotated by OlinkID.
#'
#' @param p.val_tbl a data frame of results generated by \code{olink_ttest()}
#' @param x_lab Optional. Character value to use as the X-axis label
#' @param olinkid_list Optional. Character vector of proteins (by OlinkID) to label in the plot. If not provided, default is to label all significant proteins.
#' @param tooltip_variable Optional. Name of column in \code{p.val_tbl} to set as \code{tooltip}, using \code{ggiraph::geom_point_interactive} instead of \code{ggplot2::geom_point}.
#' @param data_id_variable Optional. Name of column in \code{p.val_tbl} to set as \code{data_id}, using \code{ggiraph::geom_point_interactive} instead of \code{ggplot2::geom_point}.
#' @param ... Optional. Additional arguments for \code{olink_color_discrete()}
#'
#' @return An object of class "ggplot", plotting significance (y-axis) by estimated difference between groups (x-axis) for each protein.
#' @export
#' @examples
#' \donttest{
#'
#' library(dplyr)
#'
#' npx_df <- npx_data1 %>% filter(!grepl('control',SampleID, ignore.case = TRUE))
#' ttest_results <- olink_ttest(df=npx_df,
#'                              variable = 'Treatment',
#'                              alternative = 'two.sided')
#' olink_volcano_plot(ttest_results)}
#' @importFrom magrittr %>%
#' @importFrom dplyr filter pull
#' @importFrom ggplot2 ggplot aes geom_point labs geom_hline
#' @importFrom ggrepel geom_label_repel
#' @importFrom utils modifyList
#' @importFrom rlang ensym


olink_volcano_plot <- function (p.val_tbl, x_lab = "Estimate", olinkid_list = NULL, tooltip_variable = NULL, data_id_variable = NULL, ...)
{

  #checking ellipsis
  if(length(list(...)) > 0){

    ellipsis_variables <- names(list(...))

    if(length(ellipsis_variables) == 1){

      if(!(ellipsis_variables == 'coloroption')){

        stop(paste0('The ... option only takes the coloroption argument. ... currently contains the variable ',
                    ellipsis_variables,
                    '.'))

      }

    }else{

      stop(paste0('The ... option only takes one argument. ... currently contains the variables ',
                  paste(ellipsis_variables, collapse = ', '),
                  '.'))
    }
  }

  # Check interactivity
  interactivity <- FALSE
  if (!is.null(tooltip_variable) || !is.null(data_id_variable)) {
    if (!requireNamespace("ggiraph", quietly = TRUE)) {
      stop(paste0("To be able to add interactivity, the ggiraph package is required.\n",
                  "Please install ggiraph before continuing.\n\n",
                  "install.packages(\"ggiraph\")"))
    }
    interactivity <- TRUE
  }

  # Create labelling list unless given by user
  if(is.null(olinkid_list)){

    olinkid_list <- p.val_tbl %>%
      dplyr::filter(Threshold == 'Significant') %>%
      dplyr::pull(OlinkID)

  }


  volcano_plot <- p.val_tbl %>%
    ggplot2::ggplot(ggplot2::aes(x = estimate, y = -log10(p.value),
                                 color = Threshold))
  if (!interactivity) {
    volcano_plot <- volcano_plot + ggplot2::geom_point()
  }
  else {
    add_aes <- ggplot2::aes()
    if (!is.null(tooltip_variable)) {
      add_aes <- utils::modifyList(add_aes, ggplot2::aes(tooltip = !!rlang::ensym(tooltip_variable)))
    }
    if (!is.null(data_id_variable)) {
      add_aes <- utils::modifyList(add_aes, ggplot2::aes(data_id = !!rlang::ensym(data_id_variable)))
    }
    volcano_plot <- volcano_plot + ggiraph::geom_point_interactive(add_aes)
  }
  volcano_plot <- volcano_plot +
    ggplot2::labs(x = x_lab, y = "-log10(p-value)") +
    ggrepel::geom_label_repel(data = subset(p.val_tbl, OlinkID %in% olinkid_list),
                              ggplot2::aes(label = Assay), box.padding = 1, show.legend = FALSE) +
    ggplot2::geom_hline(yintercept = -log10(0.05), linetype="dotted") +
    OlinkAnalyze::set_plot_theme() +
    OlinkAnalyze::olink_color_discrete(...)


  return(volcano_plot)

}
