ARG  R_VERSION=4.4.0
FROM ghcr.io/rocker-org/tidyverse:${R_VERSION}

# System libs
RUN apt-get update \
  && apt-get install -y libglpk40 \
    libxt6 \
    texlive-latex-base \
    texlive-fonts-recommended \
    texlive-fonts-extra \
    texlive-latex-extra \
  && rm -rf /var/lib/apt/lists/*

# R packages
RUN install2.r --error \
  --deps TRUE \
  --skipinstalled \
  devtools \
  rcmdcheck \
  lintr \
  lme4 \
  bspm \
  && rm -rf /tmp/downloaded_packages

# Create the .Rprofile file to update packages from a Posit Public PM snapshot.
# This is needed to update R libraries that are outdated in the original docker
# image. The docker image for R 4.1.3 has a snapshot from 2022-04-21 and the one
# for R 4.2.3 has a snapshot from 2023-04-20. These snapshots do not host the
# latest version of certain packages. We will be using a snapshot from
# 2023-11-17 when all packages satisfy the requiered versions of OlinkAnalyze.
# 
# In addition, the docker image for R 4.2.3 is built on Ubuntu 22.04 jammy,
# while the one for R 4.1.3 is built on Ubuntu 22.04 focal. This is why we have
# the nested if statements below with different Posit Public Package Manager
# snapshots.
# 
ARG r_profile=.Rprofile
RUN if [ "$R_VERSION" = "4.2.3" ]; then \
      # For R 4.2.3
      echo "Setting up snapshot for R 4.2.3 on Ubuntu 22.04 Jammy from 2023-11-17"; \
      echo "options(repos = c(" > "$r_profile"; \
      echo "  CRAN = \"https://packagemanager.posit.co/cran/__linux__/jammy/2023-11-17\"" >> "$r_profile"; \
      echo "))" >> "$r_profile"; \
    else \
      # For R 4.1.3
      if [ "$R_VERSION" = "4.1.3" ]; then \
        echo "Setting up snapshot for R 4.1.3 on Ubuntu 20.04 Focal from 2023-11-17"; \
        echo "options(repos = c(" > "$r_profile"; \
        echo "  CRAN = \"https://packagemanager.posit.co/cran/__linux__/focal/2023-11-17\"" >> "$r_profile"; \
        echo "))" >> "$r_profile"; \
      else \
        echo "Running on R > 4.2.3. Nothing to update!"; \
      fi \
    fi

ENV _R_CHECK_FORCE_SUGGESTS_=FALSE

COPY OlinkAnalyze/DESCRIPTION /src/DESCRIPTION

RUN R -e "devtools::install_dev_deps(pkg = '/src', dependencies = TRUE)"

ENTRYPOINT ["R", "--vanilla"]
