## code to prepare internal dataset `column_name_dict` goes here
## based on https://r-pkgs.org/data.html#sec-data-sysdata

## alternative names for columns of Olink files
##
## IMPORTANT:
## presence of NA in the vector of alternative names indicates that the column
## can be missing

column_name_dict <- list(
  # sample
  sample_id =     c("SampleID",
                    "sampleid",
                    "sample_id"),
  sample_type =   c("Sample_Type",
                    "SampleType",
                    "sample_type",
                    "sampletype",
                    NA_character_),
  # assay
  assay_type =    c("Assay_Type",
                    "AssayType",
                    "assay_type",
                    "assaytype",
                    NA_character_),
  olink_id =      c("OlinkID",
                    "OID",
                    "olinkid",
                    "oid",
                    "olink_id"),
  uniprot =       c("UniProt",
                    "uniprot"),
  assay =         c("Assay",
                    "assay"),
  panel =         c("Panel",
                    "panel"),
  # product
  plate_id =      c("PlateID",
                    "plateid",
                    "plate_id"),
  panel_version = c("Panel_Lot_Nr",
                    "panel_lot_nr",
                    "Panel_Version",
                    "panel_version",
                    "PanelVersion",
                    "panelversion",
                    "DataAnalysisRefID",
                    "data_analysis_ref_id",
                    "dataanalysisrefid"),
  # quantification
  lod =           c("LOD",
                    "lod",
                    "Plate LOD",
                    "Plate_LOD",
                    "PlateLOD",
                    "plate lod",
                    "plate_lod",
                    "platelod",
                    "Max LOD",
                    "Max_LOD",
                    "MaxLOD",
                    "max lod",
                    "max_lod",
                    "maxlod",
                    "LODNPX",
                    "lodnpx",
                    "LOD_NPX",
                    "lod_npx",
                    NA_character_),
  quant =         c("NPX",
                    "npx",
                    "Quantified",
                    "Quantified_value",
                    "quantified",
                    "quantified_value",
                    "Ct",
                    "ct"),
  count =         c("Count",
                    "count",
                    NA_character_),
  # QC
  qc_warning =    c("QC_Warning",
                    "SampleQC",
                    "qc_warning",
                    "sample_qc"),
  assay_warn =    c("Assay_Warning",
                    "assay_warning",
                    "AssayQC",
                    "assay_qc",
                    NA_character_),
  normalization = c("Normalization",
                    "normalization",
                    NA_character_)
)
