# readme ----

# This script uses the raw data files:
# 1. inst/extdata/npx_data2_meta.csv
# 2. inst/extdata/npx_data2.xlsx
# to generate the sample dataset data/npx_data2.rda which is used throughout
# OlinkAnalyze.
#
# As this script did not exist prior to 2024-04-08, we have stored the original
# npx_data2.rds file under data-raw/ref_npx_data2.rds to compare to the dataset
# generated by this script.
#
# A new data/npx_data2.rda will be generated ONLY IF npx_data2 from this script
# matches ref_npx_data2!
#

# manifest ----

## load manifest ----

manifest_data2_file <- system.file("extdata",
                                   "npx_data2_meta.csv",
                                   package = "OlinkAnalyze",
                                   mustWork = TRUE)

manifest_data2 <- read.delim(
  file = manifest_data2_file,
  header = TRUE,
  sep = ";",
  na.strings = c("", "NA")
)

## modify manifest ----

manifest_data2 <- manifest_data2 |>
  # remove duplicate entries
  dplyr::distinct() |>
  # make all columns character vectors
  dplyr::mutate(
    dplyr::across(
      dplyr::everything(),
      ~ as.character(.x)
    )
  ) |>
  # rename the project to "data2" to match reference
  dplyr::mutate(
    Project = dplyr::if_else(is.na(.data[["Project"]]),
                             NA_character_,
                             "data2")
  )

## clean up
rm(manifest_data2_file)

# npx_data2 ----

# note that this data frame is quite large and for the purposes of this package
# we will use only 2 panels.
#
# we want the outcome from this section to be identical to the reference data
# frame npx_data2

## load npx_data2 ----

npx_data2_file <- system.file("extdata",
                              "npx_data2.xlsx",
                              package = "OlinkAnalyze",
                              mustWork = TRUE)

npx_data2 <- read_npx(filename = npx_data2_file,
                      out_df = "tibble",
                      long_format = FALSE,
                      data_type = "NPX",
                      olink_platform = "Target 96")
# ignore the following:
# 1. warning message about 2 duplicate samples. this is driven by control
#    samples

## modify npx_data2 ----

npx_data2 <- npx_data2 |>
  # keep only data from 2 panels: cardiometabolic and inflammation
  dplyr::filter(
    .data[["Panel"]] %in% c("Olink Target 96 CARDIOMETABOLIC",
                            "Olink Target 96 INFLAMMATION")
  ) |>
  # make Panel as a title: first letter of every word capital and the remaining
  # lower case
  dplyr::mutate(
    Panel = .data[["Panel"]] |>
      stringr::str_replace(pattern = "Target 96 ", replacement = "") |>
      stringr::str_to_title()
  ) |>
  # Panel_Version is NA from read_npx as it cannot be determined from the input
  # file, so we have to input it manually
  dplyr::mutate(
    Panel_Version = dplyr::case_match(
      .data[["Panel"]],
      "Olink Cardiometabolic" ~ "v.1201",
      "Olink Inflammation" ~ "v.1002",
      .default = NA_character_
    )
  ) |>
  # Convert NPX, LOD and MissingFreq to numeric and keep only 5 sign digits
  dplyr::mutate(
    dplyr::across(
      dplyr::all_of(
        c("NPX", "LOD", "MissingFreq")
      ),
      ~ as.numeric(.x)
    )
  ) |>
  # remove columns missing from the reference npx_data2
  dplyr::select(
    -dplyr::all_of(
      "Olink NPX Signature Version"
    )
  )

## join with manifest ----

npx_data2 <- npx_data2 |>
  # bring in sample info from manifest file
  dplyr::inner_join(
    manifest_data2,
    by = "SampleID",
    relationship = "many-to-one"
  )

# clean up
rm(npx_data2_file, manifest_data2)

# compare to reference npx_data2 ----

## load reference npx_data2 ----

ref_npx_data2_file <- system.file("data-raw",
                                  "ref_npx_data2.rds",
                                  package = "OlinkAnalyze",
                                  mustWork = TRUE)

ref_npx_data2 <- readRDS(ref_npx_data2_file) |>
  dplyr::mutate(
    .row_id = dplyr::row_number()
  )

rm(ref_npx_data2_file)

## modify npx_data2 ----

npx_data2 <- npx_data2 |>
  dplyr::left_join(
    ref_npx_data2 |>
      dplyr::select(
        dplyr::all_of(
          c("SampleID", "Index", "OlinkID", "Panel_Version", "PlateID",
            "Panel", ".row_id")
        )
      ),
    by = c("SampleID", "OlinkID", "Panel_Version", "PlateID", "Panel"),
    relationship = "one-to-one"
  ) |>
  dplyr::arrange(
    .data[[".row_id"]]
  ) |>
  dplyr::select(
    -dplyr::all_of(".row_id")
  ) |>
  dplyr::select(
    dplyr::any_of(
      names(ref_npx_data2)
    )
  )

ref_npx_data2 <- ref_npx_data2 |>
  dplyr::select(
    -dplyr::all_of(".row_id")
  )

# check identical ----

# at this stage npx_data2 should be identical to the reference dataset
# ref_npx_data2.

stopifnot(
  npx_data2_eq <- all.equal(target = ref_npx_data2,
                            current = npx_data2,
                            check.attributes = TRUE,
                            check.names = TRUE)
)

testthat::expect_equal(
  npx_data2,
  ref_npx_data2
)

#### IMPORTANT
# It is extremely important that the two datasets are identical with some minor
# rounding tolerance!!

# save to data/npx_data2.rda ----

if (npx_data2_eq == TRUE) {
  usethis::use_data(npx_data2,
                    overwrite = TRUE,
                    compress = "xz",
                    version = 2L)
}
