# readme ----

# This script uses the raw data files:
# 1. inst/extdata/npx_data1_meta_original.csv
# 2. inst/extdata/npx_data1_original.xlsx
# to generate the sample dataset data/npx_data1.rda which is used throughout
# OlinkAnalyze.
#
# As this script did not exist prior to 2024-04-08, we have stored the original
# npx_data1.rds file under data-raw/ref_npx_data1.rds to compare to the dataset
# generated by this script.
#
# A new data/npx_data1.rda will be generated ONLY IF npx_data1 from this script
# matches ref_npx_data1!
#

# manifest ----

## load manifest ----

manifest_data1_file <- system.file("extdata",
                                   "npx_data1_meta.csv",
                                   package = "OlinkAnalyze",
                                   mustWork = TRUE)

manifest_data1 <- read.delim(
  file = manifest_data1_file,
  header = TRUE,
  sep = ";",
  na.strings = c("", "NA")
)

## modify manifest ----

manifest_data1 <- manifest_data1 |>
  # remove duplicate entries
  dplyr::distinct() |>
  # make all columns character vectors
  dplyr::mutate(
    dplyr::across(
      dplyr::everything(),
      ~ as.character(.x)
    )
  ) |>
  # rename the project to "data1" to match reference
  dplyr::mutate(
    Project = dplyr::if_else(is.na(.data[["Project"]]),
                             NA_character_,
                             "data1")
  )

## clean up
rm(manifest_data1_file)

# npx_data1 ----

# note that this data frame is quite large and for the purposes of this package
# we will use only 2 panels.
#
# we want the outcome from this section to be identical to the reference data
# frame npx_data1

## load npx_data1 ----

npx_data1_file <- system.file("extdata",
                              "npx_data1.xlsx",
                              package = "OlinkAnalyze",
                              mustWork = TRUE)

npx_data1 <- read_npx(filename = npx_data1_file,
                      out_df = "tibble",
                      long_format = FALSE,
                      data_type = "NPX",
                      olink_platform = "Target 96")
# ignore the following:
# 1. warning message about 2 duplicate samples. this is driven by control
#    samples
# 2. warning that the olink platform could not be determined from the file and
#    that the use input "Target 96" should be accepted

## modify npx_data1 ----

npx_data1 <- npx_data1 |>
  # keep only data from 2 panels: cardiometabolic and inflammation
  dplyr::filter(
    .data[["Panel"]] %in% c("Olink CARDIOMETABOLIC", "Olink INFLAMMATION")
  ) |>
  # make Panel as a title: first letter of every word capital and the remaining
  # lower case
  dplyr::mutate(
    Panel = stringr::str_to_title(string = .data[["Panel"]])
  ) |>
  # Panel_Version is NA from read_npx as it cannot be determined from the input
  # file, so we have to input it manually
  dplyr::mutate(
    Panel_Version = dplyr::case_match(
      .data[["Panel"]],
      "Olink Cardiometabolic" ~ "v.1201",
      "Olink Inflammation" ~ "v.1002",
      .default = NA_character_
    )
  ) |>
  # Convert NPX, LOD and MissingFreq to numeric and keep only 5 sign digits
  dplyr::mutate(
    dplyr::across(
      dplyr::all_of(
        c("NPX", "LOD", "MissingFreq")
      ),
      ~ as.numeric(.x)
    )
  ) |>
  # remove columns missing from the reference npx_data1
  dplyr::select(
    -dplyr::all_of(
      "Olink NPX Signature Version"
    )
  )

## join with manifest ----

npx_data1 <- npx_data1 |>
  # bring in sample info from manifest file
  dplyr::inner_join(
    manifest_data1,
    by = "SampleID",
    relationship = "many-to-one"
  )

## df to order npx_data1 ----

# the table below is exported from:
# npx_data1 |> dplyr::distinct(SampleID, Index, PlateID)
# using the original npx_data1
npx_data1_order <- dplyr::tibble(
  SampleID = c("A1", "A2", "A3", "A4", "A5", "A6", "A7", "A8",
               "CONTROL_SAMPLE_AS 1", "A9", "A10", "A11", "A12", "A13", "A14",
               "A15", "A16", "A17", "A18", "CONTROL_SAMPLE_AS 2", "A19", "A20",
               "A21", "A22", "A23", "A24", "A25", "A26", "A27", "A28", "A29",
               "A30", "A31", "A32", "A33", "A34", "A35", "A36", "A37", "A38",
               "A39", "A40", "A41", "A42", "A43", "A44", "A45", "A46", "A47",
               "A48", "A49", "A50", "A51", "A52", "A53", "A54", "A55", "A56",
               "A57", "A58", "A59", "A60", "A61", "A62", "A63", "A64", "A65",
               "A66", "A67", "A68", "A69", "A70", "A71", "A72", "A73", "A74",
               "A75", "A76", "A77", "B1", "B2", "B3", "B4", "B5", "B6", "B7",
               "B8", "B9", "B10", "CONTROL_SAMPLE_AS 1", "B11", "B12", "B13",
               "B14", "B15", "B16", "B17", "B18", "B19", "B20",
               "CONTROL_SAMPLE_AS 2", "B21", "B22", "B23", "B24", "B25", "B26",
               "B27", "B28", "B29", "B30", "B31", "B32", "B33", "B34", "B35",
               "B36", "B37", "B38", "B39", "B40", "B41", "B42", "B43", "B44",
               "B45", "B46", "B47", "B48", "B49", "B50", "B51", "B52", "B53",
               "B54", "B55", "B56", "B57", "B58", "B59", "B60", "B61", "B62",
               "B63", "B64", "B65", "B66", "B67", "B68", "B69", "B70", "B71",
               "B72", "B73", "B74", "B75", "B76", "B77", "B78", "B79", "A1",
               "A2", "A3", "A4", "A5", "A6", "A7", "A8", "CONTROL_SAMPLE_AS 1",
               "A9", "A10", "A11", "A12", "A13", "A14", "A15", "A16", "A17",
               "A18", "CONTROL_SAMPLE_AS 2", "A19", "A20", "A21", "A22", "A23",
               "A24", "A25", "A26", "A27", "A28", "A29", "A30", "A31", "A32",
               "A33", "A34", "A35", "A36", "A37", "A38", "A39", "A40", "A41",
               "A42", "A43", "A44", "A45", "A46", "A47", "A48", "A49", "A50",
               "A51", "A52", "A53", "A54", "A55", "A56", "A57", "A58", "A59",
               "A60", "A61", "A62", "A63", "A64", "A65", "A66", "A67", "A68",
               "A69", "A70", "A71", "A72", "A73", "A74", "A75", "A76", "A77",
               "B1", "B2", "B3", "B4", "B5", "B6", "B7", "B8", "B9", "B10",
               "CONTROL_SAMPLE_AS 1", "B11", "B12", "B13", "B14", "B15", "B16",
               "B17", "B18", "B19", "B20", "CONTROL_SAMPLE_AS 2", "B21", "B22",
               "B23", "B24", "B25", "B26", "B27", "B28", "B29", "B30", "B31",
               "B32", "B33", "B34", "B35", "B36", "B37", "B38", "B39", "B40",
               "B41", "B42", "B43", "B44", "B45", "B46", "B47", "B48", "B49",
               "B50", "B51", "B52", "B53", "B54", "B55", "B56", "B57", "B58",
               "B59", "B60", "B61", "B62", "B63", "B64", "B65", "B66", "B67",
               "B68", "B69", "B70", "B71", "B72", "B73", "B74", "B75", "B76",
               "B77", "B78", "B79"),
  PlateID = c(
    rep(x = "Example_Data_13_INFI.csv", times = 79L),
    rep(x = "Example_Data_14_INFI.csv", times = 81L),
    rep(x = "Example_Data_1_CAM.csv", times = 79L),
    rep(x = "Example_Data_2_CAM.csv", times = 81L)
  ),
  Index = rep(x = 1L:160L, times = 2L)
)

npx_data1 <- npx_data1 |>
  dplyr::left_join(
    npx_data1_order,
    by = c("SampleID", "PlateID"),
    relationship = "many-to-one"
  )
rm(npx_data1_order)

## order dataset ----

npx_data1 <- npx_data1 |>
  # order df to match reference npx_data1
  dplyr::arrange(
    .data[["Panel"]], .data[["OlinkID"]], .data[["Index"]]
  ) |>
  dplyr::select(
    dplyr::all_of(
      c("SampleID", "Index", "OlinkID", "UniProt", "Assay", "MissingFreq",
        "Panel_Version", "PlateID", "QC_Warning", "LOD", "NPX", "Subject",
        "Treatment", "Site", "Time", "Project", "Panel")
    )
  )

# clean up
rm(npx_data1_file, manifest_data1)

# compare to reference npx_data1 ----

## load reference npx_data1 ----

ref_npx_data1_file <- system.file("data-raw",
                                  "ref_npx_data1.rds",
                                  package = "OlinkAnalyze",
                                  mustWork = TRUE)

ref_npx_data1 <- readRDS(ref_npx_data1_file)

# clean up
rm(ref_npx_data1_file)

# check identical ----

# at this stage npx_data1 should be identical to the reference dataset
# ref_npx_data1.

stopifnot(
  npx_data1_eq <- all.equal(target = ref_npx_data1,
                            current = npx_data1,
                            check.attributes = TRUE,
                            check.names = TRUE)
)

testthat::expect_equal(
  object = npx_data1,
  expected = ref_npx_data1
)

#### IMPORTANT
# It is extremely important that the two datasets are identical with some minor
# rounding tolerance!!

# save to data/npx_data1.rda ----

if (npx_data1_eq == TRUE) {
  usethis::use_data(npx_data1,
                    overwrite = TRUE,
                    compress = "xz",
                    version = 2L)
}
