# readme ----

# This script creates a synthetic manifest file to generate the sample manifest
# data/manifest.rda which is used throughout OlinkAnalyze.
#
# As this script did not exist prior to 2024-04-08, we have stored the original
# manifest.rds file under data-raw/ref_manifest.rds to compare to the dataset
# generated by this script.
#
# A new data/manifest.rda will be generated ONLY IF manifest from this script
# matches ref_manifest!
#

# manifest ----

## create random manifest ----

n_subject <- 23L
n_visit <- 6L

manifest <- dplyr::tibble(
  SubjectID = rep(x = LETTERS[1L:n_subject], each = n_visit),
  Visit = rep(x = 1L:n_visit, times = n_subject)
) |>
  dplyr::mutate(
    SampleID = paste(SubjectID, Visit),
    Site = c(rep(x = "Site1", times = ceiling(n_subject / 2) * n_visit),
             rep(x = "Site2", times = floor(n_subject / 2) * n_visit))
  )

# clean up
rm(n_subject, n_visit)

# compare to reference manifest ----

## load reference manifest ----

ref_manifest_file <- system.file("data-raw",
                                 "ref_manifest.rds",
                                 package = "OlinkAnalyze",
                                 mustWork = TRUE)

ref_manifest <- readRDS(ref_manifest_file)

## check columns ----

stopifnot(
  identical(colnames(manifest), colnames(ref_manifest))
)

# clean up
rm(ref_manifest_file)

# check identical ----

# at this stage manifest should be identical to the reference dataset
# ref_manifest. We simply allow some rounding error on the 4th decimal digit.

stopifnot(
  manifest_eq <- all.equal(target = ref_manifest,
                           current = manifest,
                           tolerance = 1e-4,
                           check.attributes = TRUE,
                           check.names = TRUE)
)

#### IMPORTANT
# It is extremely important that the two datasets are identical with some minor
# rounding tolerance!!

# save to data/manifest.rda ----

if (manifest_eq == TRUE) {
  usethis::use_data(manifest,
                    overwrite = TRUE,
                    compress = "xz",
                    version = 2L)
}
