# readme ----

# This script uses the raw data files:
# 1. inst/extdata/npx_data1_meta_original.csv
# 2. inst/extdata/npx_data1_original.xlsx
# to generate the sample dataset data/npx_data1.rda which is used throughout
# OlinkAnalyze.
#
# As this script did not exist prior to 2024-04-08, we have stored the original
# npx_data1.rds file under data-raw/ref_npx_data1.rds to compare to the dataset
# generated by this script.
#
# A new data/npx_data1.rda will be generated ONLY IF npx_data1 from this script
# matches ref_npx_data1!
#

# manifest ----

## load manifest ----

manifest_data1_file <- system.file("extdata",
                                   "npx_data1_meta.csv",
                                   package = "OlinkAnalyze",
                                   mustWork = TRUE)

manifest_data1 <- read.delim(
  file = manifest_data1_file,
  header = TRUE,
  sep = ";",
  na.strings = c("", "NA")
)

## modify manifest ----

manifest_data1 <- manifest_data1 |>
  # remove duplicate entries
  dplyr::distinct() |>
  # make all columns character vectors
  dplyr::mutate(
    dplyr::across(
      dplyr::everything(),
      ~ as.character(.x)
    )
  ) |>
  # rename the project to "data1" to match reference
  dplyr::mutate(
    Project = dplyr::if_else(is.na(.data[["Project"]]),
                             NA_character_,
                             "data1")
  )

## clean up
rm(manifest_data1_file)

# npx_data1 ----

# note that this data frame is quite large and for the purposes of this package
# we will use only 2 panels.
#
# we want the outcome from this section to be identical to the reference data
# frame npx_data1

## load npx_data1 ----

npx_data1_file <- system.file("extdata",
                              "npx_data1.xlsx",
                              package = "OlinkAnalyze",
                              mustWork = TRUE)

npx_data1 <- read_npx(filename = npx_data1_file,
                      out_df = "tibble",
                      long_format = FALSE,
                      data_type = "NPX",
                      olink_platform = "Target 96")
# ignore the following:
# 1. warning message about 2 duplicate samples. this is driven by control
#    samples
# 2. warning that the olink platform could not be determined from the file and
#    that the use input "Target 96" should be accepted
rm(npx_data1_file)

## modify npx_data1 ----

npx_data1 <- npx_data1 |>
  # keep only data from 2 panels: cardiometabolic and inflammation
  dplyr::filter(
    .data[["Panel"]] %in% c("Olink CARDIOMETABOLIC", "Olink INFLAMMATION")
  ) |>
  # make Panel as a title: first letter of every word capital and the remaining
  # lower case
  dplyr::mutate(
    Panel = stringr::str_to_title(string = .data[["Panel"]])
  ) |>
  # Panel_Version is NA from read_npx as it cannot be determined from the input
  # file, so we have to input it manually
  dplyr::mutate(
    Panel_Version = dplyr::case_match(
      .data[["Panel"]],
      "Olink Cardiometabolic" ~ "v.1201",
      "Olink Inflammation" ~ "v.1002",
      .default = NA_character_
    )
  ) |>
  # Convert NPX, LOD and MissingFreq to numeric and keep only 5 sign digits
  dplyr::mutate(
    dplyr::across(
      dplyr::all_of(
        c("NPX", "LOD", "MissingFreq")
      ),
      ~ as.numeric(.x)
    )
  ) |>
  # remove columns missing from the reference npx_data1
  dplyr::select(
    -dplyr::all_of(
      "Olink NPX Signature Version"
    )
  )

## join with manifest ----

npx_data1 <- npx_data1 |>
  # bring in sample info from manifest file
  dplyr::inner_join(
    manifest_data1,
    by = "SampleID",
    relationship = "many-to-one"
  )
rm(manifest_data1)

# compare to reference npx_data1 ----

## load reference npx_data1 ----

ref_npx_data1_file <- system.file("data-raw",
                                  "ref_npx_data1.rds",
                                  package = "OlinkAnalyze",
                                  mustWork = TRUE)

ref_npx_data1 <- readRDS(ref_npx_data1_file)

# clean up
rm(ref_npx_data1_file)

## modify npx_data1 ----

# force npx_data1 to match order of rows from ref_npx_data1

npx_data1 <- npx_data1 |>
  dplyr::left_join(
    ref_npx_data1 |>
      dplyr::mutate(
        .row_id = dplyr::row_number()
      ) |>
      dplyr::select(
        dplyr::all_of(
          c("SampleID", "Index", "OlinkID", "Panel_Version", "PlateID",
            "Panel", ".row_id")
        )
      ),
    by = c("SampleID", "OlinkID", "Panel_Version", "PlateID", "Panel"),
    relationship = "one-to-one"
  ) |>
  dplyr::arrange(
    .data[[".row_id"]]
  ) |>
  dplyr::select(
    -dplyr::all_of(".row_id")
  ) |>
  dplyr::select(
    dplyr::all_of(
      names(ref_npx_data1)
    )
  )

# check identical ----

# at this stage npx_data1 should be identical to the reference dataset
# ref_npx_data1.

stopifnot(
  npx_data1_eq <- all.equal(target = ref_npx_data1,
                            current = npx_data1,
                            check.attributes = TRUE,
                            check.names = TRUE)
)

testthat::expect_equal(
  object = npx_data1,
  expected = ref_npx_data1
)

#### IMPORTANT
# It is extremely important that the two datasets are identical with some minor
# rounding tolerance!!

# save to data/npx_data1.rda ----

if (npx_data1_eq == TRUE) {
  usethis::use_data(npx_data1,
                    overwrite = TRUE,
                    compress = "xz",
                    version = 2L)
}
