#'Easy volcano plot with Olink theme
#'
#'Creates a volcano plot using the results of the olink_ttest function. The estimated difference is plotted on the x-axis and the p-value on the y-axis. Horizontal dotted line indicates a p-value of 0.05. Significant proteins are colored based on a Benjamini-Hochberg adjusted p-value cutoff of 0.05.
#'
#' @param p.val_tbl a data frame of results generated by olink_ttest()
#' @param x_lab Optional. Character value to use as the X-axis label
#' @param olinkid_list Optional. Character vector of proteins (by OlinkID) to label in the plot. If not provided, default is to label all significant proteins.
#' @return An object of class "ggplot"
#' @export
#' @examples
#' \donttest{ttest_results <- olink_ttest(df=npx.data, variable = 'Group', alternative = 'two.sided')
#' volcano_plot(ttest_results)}


olink_volcano_plot <- function (p.val_tbl, x_lab = "Estimate", olinkid_list = NULL)
{

  if(is.null(olinkid_list)){

    olinkid_list <- p.val_tbl %>%
      filter(Threshold == 'Significant') %>%
      pull(OlinkID)

  }



  volcano_plot <- p.val_tbl %>%
    ggplot(aes(x = estimate, y = -log10(p.value), color = Threshold)) +
    geom_point() +
    labs(x = x_lab, y = "-log10(p-value)") +
    ggrepel::geom_label_repel(data = subset(p.val_tbl, OlinkID %in% olinkid_list), aes(label = Assay), box.padding = 1, show.legend = F) +
    geom_hline(yintercept = -log10(0.05), linetype="dotted") +
    theme_bw() +
    theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
    theme(panel.border = element_blank(), axis.line = element_line(size = 0.5)) +
    theme(strip.background = element_rect(fill = "white"),
          strip.text = element_text(size = 8),
          strip.text.x = element_text(size = 13))


  return(volcano_plot)

}
