# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on: 
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'CRAN*'

name: CRAN checks

jobs:

  CRAN-check:
    runs-on: ubuntu-latest
    strategy:      
      fail-fast: false    
      matrix: 
        config:
          - {os: ubuntu-latest, r: 'release'}

  
    runs-on: ${{ matrix.config.os }}
    timeout-minutes: 120       

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      _R_CHECK_FORCE_SUGGESTS_: false
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          use-public-rspm: true            

      - name: Set BioC version
        run: |
          install.packages("remotes")
          forenv <- paste("R_BIOC_VERSION=", as.character(remotes::bioc_version()), sep = "")
          write(forenv, file = Sys.getenv("GITHUB_ENV"), append = TRUE) # Store current value to ENV          
        shell: Rscript {0}
      
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          working-directory: OlinkAnalyze
          extra-packages: any::rcmdcheck, pillar, any::devtools

      - name: Record notes
        run: |
          setwd("OlinkAnalyze")
          results <- devtools::check(error_on = "never")
          print(results$errors)
          print(results$warnings)
          print(results$notes)
        shell: Rscript {0}





