# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches:
      - optimization_develop
      - optimization_develop_clean

name: lint-zero

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          working-directory: OlinkAnalyze
          extra-packages: lintr

      - name: Lint current commit
        run: |
          pkgload::load_all(path = "OlinkAnalyze")
          ll <- lintr::lint_package()
          print(paste("Number of detected lints:", length(ll)))
          print(ll)
          stopifnot(length(ll) == 0)
        shell: Rscript {0}