on: [pull_request]

name: R-CMD-check-docker

jobs:
  R-CMD-check-docker:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        r_version: ["4.1.3", "4.2.3", "4.3.3", "4.4.2"]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build docker image
        uses: docker/build-push-action@v4
        with:
          push: false
          tags: oa:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: docker/Dockerfile_for_tests
          load: true
          build-args: R_VERSION=${{matrix.r_version}}
      -
        name: Run rcmdcheck
        run: |
          echo "rcmdcheck::rcmdcheck(path = '/OA', check_dir = '/check', error_on = 'warning')" | docker run -i -v "$(pwd)/OlinkAnalyze":/OA -v "$(pwd)/check":/check oa:latest
      -
        name: Upload check results
        if: failure()
        uses: actions/upload-artifact@main
        with:
          name: docker-r${{ matrix.config.r }}-check-results
          path: check
