on:
  push:
    branches:
      - 'main'
      - 'develop'
      - 'optimization_develop'
      - 'optimization_main'
      - 'optimization_develop_ci_coverage'

name: Update coverage badge

jobs:
  update-coverage-badge:
    name: update-coverage-badge
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      GITHUB_PAT: ${{ secrets.OA_PAT }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
          token: ${{ secrets.OA_PAT }}

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::pak, any::remotes, any::stringr, any::covr, local::.
          working-directory: OlinkAnalyze

      - name: Test coverage badge
        run: |
          source("test_coverage/update_readme_coverage_badge.R")
        shell: Rscript {0}

      - name: Commit changes if README is updated
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git commit -am 'Update coverage badge in README' || echo "No changes to commit"

      - name: Pull first
        run: |
          git pull

      - name: Push
        run: |
          git push origin
