on:
  push:
    branches:
      - 'main'
      - 'develop'
      - 'optimization_develop'
      - 'optimization_main'
      - 'optimization_develop_ci_coverage'

name: test-coverage-and-render

jobs:
  test-coverage-and-render:
    name: test-coverage-and-render
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      GITHUB_PAT: ${{ secrets.OA_PAT }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.OA_PAT }}

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::pak, any::remotes, any::stringr, any::covr, any::devtools, any::rmarkdown, local::.
          working-directory: OlinkAnalyze
          
      - name: Test coverage badge
        run: |
          source("test_coverage/update_readme_coverage_badge.R")
        shell: Rscript {0}

      - name: Commit changes if README is updated
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git commit -am 'Update coverage badge in README' || echo "No changes to commit"
          
      - name: Render Rmarkdown files
        run: |
          RMD_PATH=($(find . -iname "*.rmd" | grep -v vignette || echo "No Rmd found"))
          Rscript -e 'for (f in commandArgs(TRUE)) if (file.exists(f)) rmarkdown::render(f)' ${RMD_PATH[*]}

      - name: Commit results
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git commit -am 'Re-build Rmarkdown files' || echo "No changes to commit"

      - name: Pull first
        run: |
          git pull

      - name: Push
        run: |
          git push origin
